### PR TITLE
fix interrupt signal to gracefully shutdown

### PR DESCRIPTION
**Pull request by nonbody**
previous one, i tested gracefully shutdown and i found it is not work. so i fix some code and it is ok.

app.listen should be running in goroutine. channel waiting for interrupt signal to gracefully shutdown

### CODE REVIEW

**Comment by codemicro** [comment]
Hi @nonbody!
Can you explain the reasoning behind this PR?

**Comment by nonbody** [comment]
previous one, i tested gracefully shutdown and i found it have not work. so i fix some code and it is ok.

**Comment by nonbody** [comment]
app.listen should be running in goroutine. channel waiting for interrupt signal to gracefully shutdown

**Comment by codemicro** [comment]
This example worked perfectly fine for me. How did it not work for you, out of interest? It could be that Fiber was not shutting down because there were connections open, for example.

**Comment by nonbody** [comment]
> This example worked perfectly fine for me. How did it not work for you, out of interest? It could be that Fiber was not shutting down because there were connections open, for example.

hhm... i found it shutdown immediately and force close connection from my client (curl)

**Comment by nonbody** [comment]
> > This example worked perfectly fine for me. How did it not work for you, out of interest? It could be that Fiber was not shutting down because there were connections open, for example.
> 
> my GET hanlder time.sleep 5 sec. so my client access and waiting... and now i interupt signal
> hhm... i found it shutdown immediately and my client connection received failed (curl)

in my opinion, it should be waiting until done and shutdown... rigth?

**Comment by codemicro** [comment]
Thanks for the PR!

**Pull request merged**
