### PR TITLE
Add memgraph and fiber recipe 

### PR DESCRIPTION
**Pull request by antejavor**
Hi there. The idea is to add a Memgraph snippet to Fiber recipes. 

It currently includes: 

- Connecting to Memgraph via GO driver (neo4j) 
- Get request for getting specific nodes and its connections from Memgraph 
- Get request for getting the whole graph from Memgraph

### CODE REVIEW

**Comment by gaby** [comment]
@antejavor Just lets us know when its ready for review. Thanks!

**Comment by antejavor** [comment]
@gaby Sure, let's make a review, was on AL, sorry for a bit of delay.

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
Pls add a README in the memgraph example with some information

**Comment by ReneWerner87** [comment]
@antejavor can you pls refresh and add the readme

**Comment by antejavor** [comment]
Hi @ReneWerner87, sure will do it during the day.

**Comment by antejavor** [comment]
@ReneWerner87 the README file has been added.

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
