### PR TITLE
New Boilerplate

### PR DESCRIPTION
**Pull request by solrac97gr**
# JWT+Mongo+Docker+Nginx 🚀

## Freatures

- **JWT** : Custom middleware for JWT auth
- **Mongo** : Connection with mongodb and configuration file with the possibility of changing the environment
- **Docker and Nginx** : Deploy in docker using 5 replicas and load balancer with Nginx
- **Logger** : Request logger

## Endpoints

| Name         | Rute      | Parameters | State     | Protected | Method |
| ------------ | --------- | ---------- | --------- | --------- | ------ |
| Register     | /register | No         | Completed | No        | POST   |
| Login        | /login    | No         | Completed | No        | POST   |
| Get Profile  | /profile  | id         | Completed | Yes       | GET    |
| Edit Profile | /profile  | No         | Completed | Yes       | PUT    |

### CODE REVIEW

**Comment by solrac97gr** [comment]
@koddr Yes of course I will do the unit tests, ASAP and I will do the pull request again. This weekend I can work on it

**Comment by solrac97gr** [comment]
@koddr is it strictly necessary do the test for make the pull request?

**Comment by Fenny** [comment]
Sorry for the late merge, awesome work 👍 Test cases are always a good practice, but we have multiple examples without.

**Comment by solrac97gr** [comment]
Perfect, anyway I will try to have them soon and I will send a pull request with those improvements again.

**Pull request merged**
