### PR TITLE
gorm mysql added

### PR DESCRIPTION
**Pull request by webuti**
I added mysql connect example using go and orm.

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Thanks, don't forget the link in the readme of the root directory and a readme in our new folder.

Would also be mega cool if you could add some unittests, most people always wonder what they should look like.

**Comment by webuti** [comment]
I thought I'd give a quick start @ReneWerner87

**Comment by ReneWerner87** [comment]
Ok

**Comment by webuti** [comment]
Readme added, (https://github.com/gofiber/recipes/tree/master/gorm-postgres) I started by reviewing gorm-postgres, I made some changes that I thought would be more accurate @ReneWerner87

**Comment by ReneWerner87** [comment]
Don't forget https://github.com/gofiber/recipes/blob/master/README.md#-table-of-contents

**Comment by webuti** [comment]
> Don't forget https://github.com/gofiber/recipes/blob/master/README.md#-table-of-contents

I added it now, I overlooked it

**Review by ReneWerner87 — APPROVED** [review]

**Pull request merged**
