### PR TITLE
Update book.go

### PR DESCRIPTION
**Pull request by lulungsatrioprayuda**
change type from bson to json at Book struct

### CODE REVIEW

**Review by ReneWerner87 — CHANGES_REQUESTED** [review]
2 times json in the same line is not right
bson is for the mongo dependencie

**Comment by ReneWerner87** [comment]
https://www.mongodb.com/docs/drivers/go/current/fundamentals/bson/

**Comment by lulungsatrioprayuda** [comment]
oh i see, sorry about that sir

**Review by lulungsatrioprayuda — COMMENTED** [review]
the correct one is bson,  because json is already use at first params

**Comment by ReneWerner87** [comment]
so can we close the PR ?

**Comment by lulungsatrioprayuda** [comment]
yes of course sir

**Pull request closed without merging**
