### PR TITLE
Provides an example on how to load x509 certificate from PKCS12 store type

### PR DESCRIPTION
**Pull request by jatindersinghh**
Provides an example on how to load x509 certificate from a PKCS12 store type

### CODE REVIEW

**Comment by koddr** [comment]
@jatindersinghh hi!

Thx to share recipe! When @Fenny approve, we will merge this.

**Comment by Fenny** [comment]
If you could add a link in the README.md I will merge it 👍

**Comment by jatindersinghh** [comment]
Done! Thanks.

**Comment by jatindersinghh** [comment]
Phew. Done!

**Comment by Fenny** [comment]
@jatindersinghh thanks!

**Pull request merged**
