### PR TITLE
Hexagonal Architecture with Fiber framework.

### PR DESCRIPTION
**Pull request by charity1475**
A simple implementation of hexagonal architecture  with ports and adapters using fiber framework.

### CODE REVIEW

**Comment by ReneWerner87** [comment]
@charity1475 thanks for the PR

[ ] can you add a README and link it in the readme in the rootfolder?
[ ] please add some comments above the code places
[ ] (optional) - mostly people ask how they can realize unittests, if you would write some of them, it would probably help a lot of people

**Comment by charity1475** [comment]
I have added a README and required Comments

**Comment by ReneWerner87** [comment]
please fix the comments from the hound, not just resolving without adjustment

**Comment by charity1475** [comment]
i have added prefixes to all comments required

**Pull request merged**
