### PR TITLE
feature: Gorm fiber and monitor structure

### PR DESCRIPTION
**Pull request by LfJohnVo**

### CODE REVIEW

**Comment by LfJohnVo** [comment]
[feature: Gorm fiber and monitor structure]

**Comment by ReneWerner87** [comment]
thx
@LfJohnVo pls check the review hints from "hound" and fix it

**Comment by ReneWerner87** [comment]
@LfJohnVo any progress on the review hints ?

**Comment by LfJohnVo** [comment]
@ReneWerner87  hey! im actually updating this branch and i then push :D

**Review by gaby — COMMENTED** [review]
@LfJohnVo Can you add antry for this PR in .github/dependabot.yml and the readme file.

**Comment by ReneWerner87** [comment]
- [ ] add antry for this PR in .github/dependabot.yml

**Comment by ReneWerner87** [comment]
> @ReneWerner87 hey! im actually updating this branch and i then push :D

pls check the review hints

**Comment by gaby** [comment]
@LfJohnVo Any plans to update this PR? Thanks

**Pull request closed without merging**
