### PR TITLE
add SPA example

### PR DESCRIPTION
**Pull request by WLun001**

### CODE REVIEW

**Comment by koddr** [comment]
@WLun001 hi!

Good to add some React/Vue/Svelte/Angular example to show it to recipe.

Can you add more complex example?

**Comment by Fenny** [comment]
It could be a bit more simplified, mind to edit @WLun001 ?

```go
	app.Static("/", "./dist")
	app.Static("*", "./dist/index.html")
```

**Comment by WLun001** [comment]
@koddr yes, I can try to add

@Fenny the reason i put it under `/web` it to serve other routes also, like `/api`.  I can edit and put the `/web` example in comment

**Comment by thomasvvugt** [comment]
Hi @WLun001 

Thanks for your pull request, note that for a SPA you can match the GET route to `/` which is the root path of the website.
@Fenny I don't know for sure, but maybe having the redirect middleware can help pointing everything else than `/api/*` back to `/`

Let me know if this helps you out!

**Pull request merged**
