### PR TITLE
Add Boilerplate as recipe

### PR DESCRIPTION
**Pull request by itsursujit**
I've tried to include everything I learn as newbie to this boilerplate. Please review and merge. 

Thanks

### CODE REVIEW

**Comment by thomasvvugt** [comment]
Hi @itsursujit,

Thanks for submitting your PR.
However, I feel like your boilerplate is a bit too advanced to include into our recipe repository.

Nevertheless, I am more than happy to include your approach for a boilerplate into our third-party list in our main repository's README file.
Make sure to create a PR for this, if it's not already in there! 🚀

**Comment by itsursujit** [comment]
@thomasvvugt Thanks will do that certainly. On main repository, https://github.com/gofiber/fiber, should I create a new heading as `Third-Party Boilerplate` as I don't see this heading on README file

**Comment by Fenny** [comment]
I personally do a replace all on all `README` files in the `.github` folder, in this case, you are looking for <https://github.com/gofiber/fiber#-third-party-middlewares>

**Comment by itsursujit** [comment]
I've created PR: https://github.com/gofiber/fiber/pull/732
Closing this PR in favor of above PR

**Pull request closed without merging**
