### PR TITLE
Add example for unit testing with fiber

### PR DESCRIPTION
**Pull request by dj95**
A new recipe how to unit test routes with fiber.

### CODE REVIEW

**Comment by quentincaffeino** [comment]
Sorry, but how is this a unit test? Isn't this a system/integration test?

**Comment by dj95** [comment]
I think it can be used for both.

The reason why I would call them unit test is, because you are able to inject mock object into the `Setup()`-function. Integration tests mostly refer to tests, that test the integration of an application e.g. with a database etc.. When you inject e.g. a mock-db into the `Setup()`-function, it would not really fit into an integration test. On the other side, when you spin up a db and just connect to it before you inject it into the `Setup()`-function, it would be an integration test.

Maybe the example is a little bit too small in order to fully depict its potential for unit testing and integration testing. 

Or do I mix up some things?

**Comment by quentincaffeino** [comment]
I understand now, thanks. You're right, for some simple examples I guess this is a fine unit test.

Then I guess my concern is with Fiber in general. I'm unable to test middlewares/routes without having fiber calling it since I need fiber.Ctx struct. That means that to test some deep test case I need to write tons of prep code. For eg. if I need to test some middleware then I need first to write code to successfully pass all the middlewares before it. But I *guess* this is still a unit-test, just requires more work.

Maybe this is a problem because tests become more bloated when you want to test some deep test case.

Would be nice if @Fenny could explain the better way to do this, if there is one.

**Comment by dj95** [comment]
You could also try to implement a kind of `SetupTestRouter()`, which gets a fiber handler as attribute and returns the configured app. In this manner, you would be able to write tests in the schema, like this pull request did, but only test one route/middleware + you minimize the boilerplate code and you are able to inject mocked dependencies.

**Pull request merged**
