### PR TITLE
added fiber:gRPC -> client:server example

### PR DESCRIPTION
**Pull request by amalshaji**
added a new recipe showing how to use fiber as a client to a gRPC server

### CODE REVIEW

**Comment by Fenny** [comment]
Awesome work, @amalshaji did you join our Discord yet?

**Comment by amalshaji** [comment]
Not yet. Where can I find the invite?

**Comment by Fenny** [comment]
https://gofiber.io/discord

**Comment by ntreq** [comment]
@amalshaji your repo `github.com/amalshaji/fiber-grpc/proto` is no longer available. So example you provided doesn't work anymore.

**Pull request merged**
